LOAD DATA LOCAL INFILE 'Base/chegadas_2016_ufs.csv' IGNORE
INTO TABLE ufs
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES (nome, uf_id);

LOAD DATA LOCAL INFILE 'Base/chegadas_2016_visitas.csv' IGNORE
INTO TABLE visitas
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES (pais, uf_id, ano, mes, quantidade);

LOAD DATA LOCAL INFILE 'Base/cidades.csv' IGNORE
INTO TABLE cidades
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES (nome, uf_id);
