INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Iker Casillas', 'Spain', '1981-05-20', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Gerard Piqué', 'Spain', '1987-02-2', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Javi Martínez', 'Spain', '1988-09-2', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Andrés Iniesta', 'Spain', '1984-05-11', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('David Villa', 'Spain', '1981-12-3', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Xavi Hernández', 'Spain', '1980-01-25', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Fernando Torres', 'Spain', '1984-03-20', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Cesc Fàbregas', 'Spain', '1987-05-4', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Pedro	Rodríguez', 'Spain', '1987-07-28', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('David de Gea', 'Spain', '1990-11-7', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Juan Mata', 'Spain', '1988-04-28', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Xabi Alonso', 'Spain', '1981-11-25', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Sergio Ramos', 'Spain', '1986-03-30', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Sergio Busquets', 'Spain', '1988-07-16', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Koke Merodio', 'Spain', '1992-01-8', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Jordi Alba', 'Spain', '1989-03-21', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Diego Costa', 'Spain', '1988-10-7', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Santi Cazorla', 'Spain', '1984-12-13', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('David Silva', 'Spain', '1986-01-8', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('César Azpilicueta', 'Spain', '1989-08-28', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Sergi Roberto', 'Spain', '1992-02-7', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('David de Gea', 'Spain', '1990-11-7', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Thiago Alcântara', 'Spain', '1991-04-11', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Marco Asensio', 'Spain', '1996-01-21', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Álvaro Morata', 'Spain', '1992-10-23', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Iago Aspas', 'Spain', '1987-08-1', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Dani Carvajal', 'Spain', '1992-01-11', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Isco Suárez', 'Spain', '1992-04-21', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Ander Herrera', 'Spain', '1989-08-14', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Claudio Bravo', 'Chile', '1983-04-13', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Alexis Sánchez', 'Chile', '1988-12-19', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Arturo Vidal', 'Chile', '1987-05-22', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Arjen Robben', 'Netherlands', '1984-01-23', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Memphis Depay', 'Netherlands', '1994-02-13', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Ivan Rakitic', 'Croatia', '1988-03-10', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Luka Modric', 'Croatia', '1985-09-9', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Mateo Kovacic', 'Croatia', '1994-05-6', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Javier Hernández', 'Mexico', '1988-06-1', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Guillermo Ochoa', 'Mexico', '1985-07-13', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('James Rodríguez', 'Colombia', '1991-07-12', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Juan Cuadrado', 'Colombia', '1988-05-26', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Radamel Falcao García', 'Colombia', '1986-02-10', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Shinji Kagawa', 'Japan', '1989-03-17', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Antoine Griezmann', 'France', '1991-03-21', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Paul Pogba', 'France', '1993-03-15', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('NGolo Kanté', 'France', '1991-03-29', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Karim Benzema', 'France', '1987-12-19', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Olivier Giroud', 'France', '1986-09-30', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Franck Ribéry', 'France', '1983-04-7', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Alexandre Lacazette', 'France', '1991-05-28', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Raphaël Varane', 'France', '1993-04-25', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Blaise Matuidi', 'France', '1987-04-9', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Samuel Umtiti', 'France', '1993-11-14', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Hugo Lloris', 'France', '1986-12-26', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Ousmane Dembélé', 'France', '1997-05-15', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Kylian Mbappé', 'France', '1998-12-20', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Anthony Martial', 'France', '1995-12-5', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Thomas Lemar', 'France', '1995-11-12', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Javier Mascherano', 'Argentina', '1984-06-8', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Nicolás Otamendi', 'Argentina', '1988-02-12', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Lionel Messi', 'Argentina', '1987-06-24', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Ángel Di María', 'Argentina', '1988-02-14', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Paulo Dybala', 'Argentina', '1993-11-15', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Sergio Agüero', 'Argentina', '1988-06-2', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Javier Pastore', 'Argentina', '1989-06-20', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Mauro Icardi', 'Argetina', '1993-02-19', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Gonzalo Higuaín', 'Argentina', '1987-12-10', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Manuel Neuer', 'Germany', '1986-03-27', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Marc-André ter Stegen', 'Germany', '1992-04-30', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Mats Hummels', 'Germany', '1988-12-16', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Joshua Kimmich', 'Germany', '1995-02-8', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Sami Khedira', 'Germany', '1987-04-4', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Julian Draxler', 'Germany', '1993-09-20', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Toni Kroos', 'Germany', '1990-01-4', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Mesut Özil', 'Germany', '1988-10-15', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Mario Götze', 'Germany', '1992-06-3', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Ilkay Gundogan', 'Germany', '1990-10-24', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Leroy Sané', 'Germany', '1996-01-11', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Jérôme Boateng', 'Germany', '1988-09-3', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Thomas Müller', 'Germany', '1989-09-13', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('André Schürrle', 'Germany', '1990-11-6', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Nélson Semedo', 'Portugal', '1993-11-16', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Pepe', 'Portugal', '1983-02-26', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Bernardo Silva', 'Portugal', '1994-08-10', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Gonçalo Guedes', 'Portugal', '1996-11-29', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Cristiano Ronaldo', 'Portugal', '1985-02-5', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Ricardo Quaresma', 'Portugal', '1983-09-26', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Thibaut Courtois', 'Belgium', '1992-05-11', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Thomas Vermaelen', 'Belgium', '1985-11-14', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Eden Hazard', 'Belgium', '1991-01-7', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Kevin De Bruyne', 'Belgium', '1991-06-28', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Romelu Lukaku', 'Belgium', '1993-05-13', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Joe Hart', 'England', '1987-04-19', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Gary Cahill', 'England', '1985-12-19', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Kyle Walker', 'England', '1990-05-28', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Ashley Young', 'England', '1985-07-9', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Jesse Lingard', 'England', '1992-12-15', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Jamie Vardy', 'England', '1987-01-11', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Marcus Rashford', 'England', '1997-10-31', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Dele Alli', 'England', '1996-04-11', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Harry Kane', 'England', '1993-07-28', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Luis Suárez', 'Uruguay', '1987-01-24', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Diego Godín', 'Uruguay', '1986-02-16', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Edinson Cavani', 'Uruguay', '1987-02-14', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Robert Lewandowski', 'Poland', '1988-08-21', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Gareth Bale', 'Wales', '1989-07-16', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Gianluigi Buffon', 'Italy', '1978-01-28', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Gianluigi Donnarumma', 'Italy', '1999-02-25', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Giorgio Chiellini', 'Italy', '1984-08-14', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Andrea Barzagli', 'Italy', '1981-05-8', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Leonardo Bonucci', 'Italy', '1987-05-1', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Lorenzo Insigne', 'Italy', '1991-06-4', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Stephan El Shaarawy', 'Italy', '1992-10-27', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Marco Verratti', 'Italy', '1992-11-5', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Ciro Immobile', 'Italy', '1990-02-20', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Francesco Totti', 'Italy', '1976-09-27', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Andrea Pirlo', 'Italy', '1979-05-19', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Zlatan Ibrahimovic', 'Sweden', '1981-10-3', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Pierre Aubameyang', 'Gabon', '1965-05-29', LAST_INSERT_ID());
INSERT INTO usuarios VALUES ();
INSERT INTO clientes VALUES ('Keylor Navas', 'Costa Rica', '1986-12-15', LAST_INSERT_ID())
